name: merge-to-dev-on-tag

on:
  push:
    branches:
      - feature/map
    tags:
      - '@D'

jobs:
  merge_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge to dev
        run: |
          git checkout dev
          git merge feature/map
          git push origin dev
