name: TAG Commit Action Front
on:
  push:
    branches:
      - feature/map
jobs:
  merge_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout feature/map branch
        uses: actions/checkout@v2
        with:
          ref: feature/map
      - name: Merge to dev branch
        if: contains(github.ref, '@D')
        run: |
          git checkout dev
          git merge feature/map
          git push origin dev
